baseURL = 'https://tabihaji.github.io/tabihaji/'
languageCode = "ja-jp"
defaultContentLanguage = "ja"
theme = "hugo-bearblog"

title = "足袋の端"

sectionPagesMenu = 'main'

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[params]
    description = "Hugoで作成されたブログです。主に禍話・トリッカルの二次創作小説を扱っています。"
    dateFormat = "2006-01-02"
    title = "足袋の端"
    favicon = "image/favicon.ico"
    hideMadeWithLine = true
    enablePostNavigator = true
