baseURL = 'https://tabihaji.github.io/tabihaji/'
languageCode = "ja-JP"
defaultContentLanguage = "ja"
enableRobotsTXT = true

title = "足袋の端"
author = "tabihaji"
copyright = "Copyright © 2026, tabihaji."

theme = "hugo-bearblog"
sectionPagesMenu = 'main'
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[params]
    description = "Hugoで作成されたブログです。主に禍話・トリッカルの二次創作小説を扱っています。"
    dateFormat = "2006-01-02"
    title = "足袋の端"
    favicon = "image/favicon.ico"
    #images = ["images/share.png"]
    hideMadeWithLine = true
    enablePostNavigator = true

[permalinks]
    blog = "/:slug/"
#    tags = "/blog/:slug"

[markup]
    [markup.highlight]
        lineNos = true
        lineNumbersInTable = false
        codeFences = true
